### ISSUE TITLE
역할 #1

### ISSUE THREAD

**Issue by GarlicCook** [GarlicCook/pM_teamProject#1]
example branch에 예제 코드 올렸는데 실행 해보시면 알겠지만 되게 단순하거든요?
frame은 이미 있는 코드에서 따로 수정할 필요 없을 것 같아 두분이서 역할 나누셔서 input view(예제에서는 starter에서 받았습니다.)만들고 추가로 예외처리만 하시면 될 것 같은데 어떻게 생각하시나요?

**Comment by kjk0719** [comment]
보드 사이즈 조절 기능을 넣으려면 frame에서 size 파라미터를 받아야 해요

**Comment by GarlicCook** [comment]
> 보드 사이즈 조절 기능을 넣으려면 frame에서 size 파라미터를 받아야 해요

예제 실행 해보셨나요?

**Comment by kjk0719** [comment]
아 example 브랜치를 지금 봤네요

**Comment by LaLa4978** [comment]
잘 돌아가는거 같아요. 예외처리는 문제를 해결할 수 없을 때 알려주는 알고리즘을 말하시는 거죠? 그 부분만 추가하면 될거 같은데

**Comment by LaLa4978** [comment]
그리고 저희 숫자가 랜덤으로 섞이는 방식으로 하는거죠?

**Comment by kjk0719** [comment]
@GarlicCook 예외처리는 어떤 것을 말씀하시는 건가요?

**Comment by kjk0719** [comment]
그리고 저희 Model, Controller, View에 따라서 역할 나눠야 돼요

**Comment by GarlicCook** [comment]
> 그리고 저희 Model, Controller, View에 따라서 역할 나눠야 돼요

예외처리는 1~10정도 외에는 입력 못 받게하는 거 등이 있겠죠.
그리고 Model은 이미 했으니 두 분께서 이미 정해진대로 역할을 하시던 알아서 정하시라는 말이였습니다.

**Comment by GarlicCook** [comment]
그리고 반드시 example에 올린대로 할 필요는 없는데 다르게 하실서면 고친부분도 commit하셔야 합니다.

**Comment by LaLa4978** [comment]
게임판 크기 2~9까지만 설정했고, 역할은 이전에 정한 대로 마무리하면 될 거 같아요.
