### ISSUE TITLE
불가능한 퍼즐 보드 생성

### ISSUE THREAD

**Issue by kjk0719** [GarlicCook/pM_teamProject#2]
<img width="272" alt="스크린샷 2024-12-13 221704" src="https://github.com/user-attachments/assets/a94882f3-8c48-4384-927b-20fb53d3d837" />

PuzzleFrame 기능 추가하고 있는 중인데 가끔 불가능한 퍼즐이 만들어지는 것 같은데 확인해 주실 수 있나요?
코드는 examplebranch에 있는 것으로 실행했습니다.

**Comment by GarlicCook** [comment]
수정했습니다
